# launch with: bundle exec jekyll serve --force_polling

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Project Rage Blog
name: Gary Huang
email: mail.gary.huang@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My development blog site for WolverineSoft Studio's Project Rage!
  It is also my first time setting up a website. In the future I am
  planning on incorporating this blog into my personal website.
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://garyhuan9.github.io/Personal # the base hostname & protocol for your site, e.g. http://example.com
github_username:  GaryHuan9

# Build settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
locale: "en-US"
plugins:
  - jekyll-feed
  - jekyll-include-cache

livereload: true
future: true

search              : true
search_full_content : true

author:
  name     : Gary Huang
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "Computer Science student interested in computer graphics and Two Steps From Hell music!"
  location : "Michigan, USA"

defaults:
  - scope:
      path: ""
    values:
      author_profile: true
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      read_time: true
      toc: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
